/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StyleRouteImport } from './routes/style'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as NewRouteImport } from './routes/new'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeckIdRouteImport } from './routes/deck.$id'
import { Route as DTokenRouteImport } from './routes/d.$token'
import { Route as DeckIdPublishRouteImport } from './routes/deck.$id.publish'
import { Route as DeckIdPreviewRouteImport } from './routes/deck.$id.preview'

const StyleRoute = StyleRouteImport.update({
  id: '/style',
  path: '/style',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckIdRoute = DeckIdRouteImport.update({
  id: '/deck/$id',
  path: '/deck/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DTokenRoute = DTokenRouteImport.update({
  id: '/d/$token',
  path: '/d/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckIdPublishRoute = DeckIdPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => DeckIdRoute,
} as any)
const DeckIdPreviewRoute = DeckIdPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => DeckIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/style': typeof StyleRoute
  '/d/$token': typeof DTokenRoute
  '/deck/$id': typeof DeckIdRouteWithChildren
  '/deck/$id/preview': typeof DeckIdPreviewRoute
  '/deck/$id/publish': typeof DeckIdPublishRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/style': typeof StyleRoute
  '/d/$token': typeof DTokenRoute
  '/deck/$id': typeof DeckIdRouteWithChildren
  '/deck/$id/preview': typeof DeckIdPreviewRoute
  '/deck/$id/publish': typeof DeckIdPublishRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/style': typeof StyleRoute
  '/d/$token': typeof DTokenRoute
  '/deck/$id': typeof DeckIdRouteWithChildren
  '/deck/$id/preview': typeof DeckIdPreviewRoute
  '/deck/$id/publish': typeof DeckIdPublishRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/dashboard'
    | '/login'
    | '/new'
    | '/signup'
    | '/sitemap.xml'
    | '/style'
    | '/d/$token'
    | '/deck/$id'
    | '/deck/$id/preview'
    | '/deck/$id/publish'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/dashboard'
    | '/login'
    | '/new'
    | '/signup'
    | '/sitemap.xml'
    | '/style'
    | '/d/$token'
    | '/deck/$id'
    | '/deck/$id/preview'
    | '/deck/$id/publish'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/dashboard'
    | '/login'
    | '/new'
    | '/signup'
    | '/sitemap.xml'
    | '/style'
    | '/d/$token'
    | '/deck/$id'
    | '/deck/$id/preview'
    | '/deck/$id/publish'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StyleRoute: typeof StyleRoute
  DTokenRoute: typeof DTokenRoute
  DeckIdRoute: typeof DeckIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/style': {
      id: '/style'
      path: '/style'
      fullPath: '/style'
      preLoaderRoute: typeof StyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$id': {
      id: '/deck/$id'
      path: '/deck/$id'
      fullPath: '/deck/$id'
      preLoaderRoute: typeof DeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$token': {
      id: '/d/$token'
      path: '/d/$token'
      fullPath: '/d/$token'
      preLoaderRoute: typeof DTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$id/publish': {
      id: '/deck/$id/publish'
      path: '/publish'
      fullPath: '/deck/$id/publish'
      preLoaderRoute: typeof DeckIdPublishRouteImport
      parentRoute: typeof DeckIdRoute
    }
    '/deck/$id/preview': {
      id: '/deck/$id/preview'
      path: '/preview'
      fullPath: '/deck/$id/preview'
      preLoaderRoute: typeof DeckIdPreviewRouteImport
      parentRoute: typeof DeckIdRoute
    }
  }
}

interface DeckIdRouteChildren {
  DeckIdPreviewRoute: typeof DeckIdPreviewRoute
  DeckIdPublishRoute: typeof DeckIdPublishRoute
}

const DeckIdRouteChildren: DeckIdRouteChildren = {
  DeckIdPreviewRoute: DeckIdPreviewRoute,
  DeckIdPublishRoute: DeckIdPublishRoute,
}

const DeckIdRouteWithChildren =
  DeckIdRoute._addFileChildren(DeckIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StyleRoute: StyleRoute,
  DTokenRoute: DTokenRoute,
  DeckIdRoute: DeckIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
